# Generated by Django 3.2.15 on 2023-01-21 15:31

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='d_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='order',
            name='d_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
