# Generated by Django 3.2.15 on 2023-01-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20230121_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='advance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
