# Generated by Django 3.2.15 on 2023-01-22 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_raw_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raw_material',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='raw_material',
            name='product',
        ),
    ]
