# Generated by Django 3.2.15 on 2023-01-23 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20230123_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raw_material',
            name='id1',
        ),
    ]
