# Generated by Django 3.2.15 on 2023-01-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_raw_material_id1'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(default='')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
